baseURL = "https://www.gogodjzhu.com"
DefaultContentLanguage = "zh" # Theme's display language, supports: en, fr, zh, zh-hant
languageCode = "zh-cn"
title = "gogodjzhu"
# copyright = "2021 gogodjzhu"
theme = "diary"

[params]
subtitle = "Don't judge, don't expect"
enableReadingTime=true

[taxonomies]
   tag = "tags"
   category = "categories"

[[menu.main]]
url = "/posts"
name = "文章"
weight = 1

[[menu.main]]
url = "/categories"
name = "专栏"
weight = 2

[[menu.main]]
url = "/tags"
name = "标签"
weight = 3